/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultBubbleIdRouteImport } from './routes/vault.$bubbleId'
import { Route as VaultBubbleIdCommandsRouteImport } from './routes/vault.$bubbleId.commands'
import { Route as VaultBubbleIdCameraRouteImport } from './routes/vault.$bubbleId.camera'
import { Route as VaultBubbleIdActivityRouteImport } from './routes/vault.$bubbleId.activity'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultBubbleIdRoute = VaultBubbleIdRouteImport.update({
  id: '/vault/$bubbleId',
  path: '/vault/$bubbleId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultBubbleIdCommandsRoute = VaultBubbleIdCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => VaultBubbleIdRoute,
} as any)
const VaultBubbleIdCameraRoute = VaultBubbleIdCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => VaultBubbleIdRoute,
} as any)
const VaultBubbleIdActivityRoute = VaultBubbleIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => VaultBubbleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vault/$bubbleId': typeof VaultBubbleIdRouteWithChildren
  '/vault/$bubbleId/activity': typeof VaultBubbleIdActivityRoute
  '/vault/$bubbleId/camera': typeof VaultBubbleIdCameraRoute
  '/vault/$bubbleId/commands': typeof VaultBubbleIdCommandsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vault/$bubbleId': typeof VaultBubbleIdRouteWithChildren
  '/vault/$bubbleId/activity': typeof VaultBubbleIdActivityRoute
  '/vault/$bubbleId/camera': typeof VaultBubbleIdCameraRoute
  '/vault/$bubbleId/commands': typeof VaultBubbleIdCommandsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vault/$bubbleId': typeof VaultBubbleIdRouteWithChildren
  '/vault/$bubbleId/activity': typeof VaultBubbleIdActivityRoute
  '/vault/$bubbleId/camera': typeof VaultBubbleIdCameraRoute
  '/vault/$bubbleId/commands': typeof VaultBubbleIdCommandsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/vault/$bubbleId'
    | '/vault/$bubbleId/activity'
    | '/vault/$bubbleId/camera'
    | '/vault/$bubbleId/commands'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/vault/$bubbleId'
    | '/vault/$bubbleId/activity'
    | '/vault/$bubbleId/camera'
    | '/vault/$bubbleId/commands'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/vault/$bubbleId'
    | '/vault/$bubbleId/activity'
    | '/vault/$bubbleId/camera'
    | '/vault/$bubbleId/commands'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VaultBubbleIdRoute: typeof VaultBubbleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$bubbleId': {
      id: '/vault/$bubbleId'
      path: '/vault/$bubbleId'
      fullPath: '/vault/$bubbleId'
      preLoaderRoute: typeof VaultBubbleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$bubbleId/commands': {
      id: '/vault/$bubbleId/commands'
      path: '/commands'
      fullPath: '/vault/$bubbleId/commands'
      preLoaderRoute: typeof VaultBubbleIdCommandsRouteImport
      parentRoute: typeof VaultBubbleIdRoute
    }
    '/vault/$bubbleId/camera': {
      id: '/vault/$bubbleId/camera'
      path: '/camera'
      fullPath: '/vault/$bubbleId/camera'
      preLoaderRoute: typeof VaultBubbleIdCameraRouteImport
      parentRoute: typeof VaultBubbleIdRoute
    }
    '/vault/$bubbleId/activity': {
      id: '/vault/$bubbleId/activity'
      path: '/activity'
      fullPath: '/vault/$bubbleId/activity'
      preLoaderRoute: typeof VaultBubbleIdActivityRouteImport
      parentRoute: typeof VaultBubbleIdRoute
    }
  }
}

interface VaultBubbleIdRouteChildren {
  VaultBubbleIdActivityRoute: typeof VaultBubbleIdActivityRoute
  VaultBubbleIdCameraRoute: typeof VaultBubbleIdCameraRoute
  VaultBubbleIdCommandsRoute: typeof VaultBubbleIdCommandsRoute
}

const VaultBubbleIdRouteChildren: VaultBubbleIdRouteChildren = {
  VaultBubbleIdActivityRoute: VaultBubbleIdActivityRoute,
  VaultBubbleIdCameraRoute: VaultBubbleIdCameraRoute,
  VaultBubbleIdCommandsRoute: VaultBubbleIdCommandsRoute,
}

const VaultBubbleIdRouteWithChildren = VaultBubbleIdRoute._addFileChildren(
  VaultBubbleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VaultBubbleIdRoute: VaultBubbleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
